# Generated by Django 5.0.6 on 2025-02-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_products_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(help_text='Name Of the Tax (eg: VAT, GST etc.)', max_length=20)),
                ('tax_value', models.FloatField(help_text='Tax Value in Percentage(%)')),
            ],
        ),
    ]
