# Generated by Django 5.0.6 on 2025-02-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_after_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='price_before_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='tax_slab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchant.tax'),
        ),
    ]
