# Generated by Django 5.0.6 on 2025-02-07 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0007_cart_cartitems'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('total_amount', models.FloatField(default=0)),
                ('total_tax', models.FloatField(default=0)),
                ('total_amount_before_tax', models.FloatField(default=0)),
                ('check_out_status', models.BooleanField(default=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('order_number', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('total_price', models.FloatField(default=0)),
                ('total_tax', models.FloatField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='merchant.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant.products')),
            ],
        ),
    ]
