# Generated by Django 5.0.6 on 2025-03-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0010_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='virtual_product',
            field=models.ImageField(blank=True, null=True, upload_to='virtual_image'),
        ),
    ]
