# Generated by Django 5.0.6 on 2025-01-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('merchant', 'merchant')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
