# Generated by Django 5.0.6 on 2025-01-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('merchant', 'merchant')], default='user', max_length=20),
        ),
    ]
